[project]
name = "angr-tainted"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "angr>=9.2.147",
    "claripy>=9.2.147",
]
